# Generated by Django 5.1.1 on 2024-10-12 16:34

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', storage=users.models.S3Storage(), upload_to='profile_pics'),
        ),
    ]
