# Generated by Django 5.1.1 on 2024-10-19 05:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_convert_choices_to_ckeditor"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="level",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("Medium", "Medium"),
                    ("hard", "Hard"),
                    ("mixed", "Mixed"),
                    ("real", "Real"),
                ],
                default="real",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pracitcequestions",
            name="choice1",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Choice 1"),
        ),
        migrations.AlterField(
            model_name="pracitcequestions",
            name="choice2",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Choice 2"),
        ),
        migrations.AlterField(
            model_name="pracitcequestions",
            name="choice3",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Choice 3"),
        ),
        migrations.AlterField(
            model_name="pracitcequestions",
            name="choice4",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Choice 4"),
        ),
        migrations.AlterField(
            model_name="pracitcequestions",
            name="choice5",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Choice 5"),
        ),
        migrations.AlterField(
            model_name="pracitcequestions",
            name="explanation",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Explanation"
            ),
        ),
    ]
