# Generated by Django 5.1.1 on 2024-10-19 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_practice_level_alter_pracitcequestions_choice1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
