# Generated by Django 5.1.1 on 2024-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0008_practice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pracitcequestions",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="practice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
