# Generated by Django 5.1.1 on 2024-10-10 10:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('short_description', models.CharField(default='No short describtion provided, you can read full description', max_length=200, verbose_name='Describe shortly what it is about')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('in_review', 'in_review'), ('posted', 'posted')], default='submitted', max_length=20)),
                ('category', models.CharField(choices=[('insight', 'Data Insights'), ('quant', 'Quant'), ('verbal', 'Verbal'), ('other', 'other')], default='topik', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=60, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tutorials', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='tutorials.tutorial')),
            ],
            options={
                'unique_together': {('user', 'tutorial')},
            },
        ),
    ]
