# Generated by Django 5.1.1 on 2024-10-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tags',
        ),
    ]
