# Generated by Django 5.1.1 on 2024-10-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_alter_multiplechoicequestion_test_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='test_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='homeworks.test'),
        ),
    ]
