# Generated by Django 5.1.1 on 2024-10-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_useranswer_test_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeworks.test'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='homeworks.testattempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='test_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='homeworks.test'),
        ),
    ]
