# Generated by Django 5.1.1 on 2024-10-19 05:40

from django.db import migrations



def convert_to_ckeditor(apps, schema_editor):
    MultipleChoiceQuestion = apps.get_model('homeworks', 'MultipleChoiceQuestion')
    for question in MultipleChoiceQuestion.objects.all():
        # Convert existing text to CKEditor format
        question.choice1 = f'<p>{question.choice1}</p>'
        question.choice2 = f'<p>{question.choice2}</p>'
        question.choice3 = f'<p>{question.choice3}</p>'
        question.choice4 = f'<p>{question.choice4}</p>'
        question.choice5 = f'<p>{question.choice5}</p>'
        if question.explanation:
            question.explanation = f'<p>{question.explanation}</p>'
        question.save()

def reverse_convert(apps, schema_editor):
    MultipleChoiceQuestion = apps.get_model('homeworks', 'MultipleChoiceQuestion')
    for question in MultipleChoiceQuestion.objects.all():
        # Remove HTML tags if needed to reverse
        question.choice1 = question.choice1.replace('<p>', '').replace('</p>', '')
        question.choice2 = question.choice2.replace('<p>', '').replace('</p>', '')
        question.choice3 = question.choice3.replace('<p>', '').replace('</p>', '')
        question.choice4 = question.choice4.replace('<p>', '').replace('</p>', '')
        question.choice5 = question.choice5.replace('<p>', '').replace('</p>', '')
        if question.explanation:
            question.explanation = question.explanation.replace('<p>', '').replace('</p>', '')
        question.save()

class Migration(migrations.Migration):
    dependencies = [
        ("homeworks", "0008_test_category_alter_multiplechoicequestion_image"),
    ]

    operations = [migrations.RunPython(convert_to_ckeditor, reverse_convert),]
