# Generated by Django 5.1.1 on 2024-10-19 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0010_test_level_alter_multiplechoicequestion_choice1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
