# Generated by Django 5.1.1 on 2024-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0011_test_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
