# Generated by Django 5.1.1 on 2024-10-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0012_alter_test_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
