# Generated by Django 5.1.1 on 2024-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0013_test_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="fa_icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon name (e.g., 'fa-calculator')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Upload SVG icon (recommended) or small image",
                null=True,
                upload_to="test_icons/",
            ),
        ),
    ]
