# Generated by Django 5.1.1 on 2024-11-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0015_remove_test_fa_icon_remove_test_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="test",
            name="type",
            field=models.CharField(
                choices=[
                    ("math", "Math"),
                    ("geometry", "geometry"),
                    ("mixed", "Mixed"),
                    ("other", "Other"),
                ],
                default="math",
                max_length=20,
            ),
        ),
    ]
