# Generated by Django 5.1.1 on 2024-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0017_test_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
